language: python
dist: xenial
python:
- '3.5'
- '3.6'
- '3.7'
- 3.8-dev
- pypy3.5
install:
- pip install pytest
script:
- pytest
deploy:
  provider: pypi
  user: "huema-ch"
  password:
    secure: DzA/tvI6mSpNsOp4EzMfNhgSJer6afxDbi2AO2oI0RYiVsAhe86qc1fIU4yX9yMJZ+7UX5l+TmmJuRQN+As4D2M9d++JADfUPw3EmYE2ksqWsu+s+aevvwjv0+uAp6qRtyzerkO5KPNhJNT60s4NYC3Ak+7qoknUOoiB6hUWz3uVqU0vTT/mjlz/y9FYd3WhBY7DPkLRgB3etMOmZDLnwwUn/F4Z9wmFLux7ftC6X8hWn7P7pQ43bC/DVpT1IosAwQrT5lqFgar7RjY6t9oK4DUztoZ4iRWqMyeJ1azPbEIluaVhz1dahZ7JzDJslJVuj1ansWJdzVu6m9c5awtzYYf/Ays+9k0noRHfWbbEJqYSz9WKcuyGKRPQb50eYl5dFSHgAdZD5bkM9zQqyZM6CABpewHlOOtTXiafbRL4YEHUewEiVLfxbMQw2J0PdrRis1comzIxZXrDf0tKnP0Y2dpj1YcHCvqPn2Jjidx7nnq+ABZSZzNPbfVs7odXcbueZWtFKeHm1k09YITx+sNjx27HMOa/hWzhRH9p3ZYBxIwblbPYxc7iIHYjy8IWNGRdzBR3bH72oH9T0QvsUJ7/5ZD3zaHuqaLCGIzpj1BXv3jB61RNlBZ0fiOq3AKeDG+xkI8/7QgCCPgl2XzU8Iq1Hzq9pVXajlvESKEKnCWgpG8=
  distributions: sdist bdist_wheel
  on:
    all_branches: true
